# Generated by Django 6.0.2 on 2026-02-04 08:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الصنف')),
                ('code', models.CharField(max_length=50, verbose_name='رمز الصنف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_global', models.BooleanField(default=False, help_text='متاح لجميع الوحدات', verbose_name='صنف عام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.category', verbose_name='الصنف الأب')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.tenant', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'صنف',
                'verbose_name_plural': 'الأصناف',
                'ordering': ['name'],
                'unique_together': {('code', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المصلحة')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='رمز المصلحة')),
                ('responsible_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المسؤول')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.tenant', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'مصلحة',
                'verbose_name_plural': 'المصالح',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='اسم المادة')),
                ('code', models.CharField(max_length=100, verbose_name='رمز المادة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('nature', models.CharField(choices=[('asset', 'مادة مجرودة (أصل)'), ('consumable', 'مادة غير مجرودة (مستهلكة)')], default='consumable', max_length=20, verbose_name='طبيعة المادة')),
                ('unit', models.CharField(choices=[('piece', 'قطعة'), ('box', 'علبة'), ('pack', 'رزمة'), ('kg', 'كيلوغرام'), ('liter', 'لتر'), ('meter', 'متر'), ('ream', 'رزمة ورق')], default='piece', max_length=20, verbose_name='وحدة القياس')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='سعر الوحدة')),
                ('min_stock', models.PositiveIntegerField(default=0, verbose_name='الحد الأدنى للمخزون')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category', verbose_name='الصنف')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.tenant', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'منتج/مادة',
                'verbose_name_plural': 'المنتجات/المواد',
                'ordering': ['name'],
                'unique_together': {('code', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'دخول'), ('out', 'خروج'), ('return', 'إرجاع'), ('adjust', 'تعديل')], max_length=10, verbose_name='نوع الحركة')),
                ('quantity', models.IntegerField(help_text='موجب للدخول، سالب للخروج', verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='سعر الوحدة')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='المرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.product', verbose_name='المنتج')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.tenant', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المورد')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='رمز المورد')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='الرقم الجبائي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.tenant', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردون',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=100, verbose_name='رقم الجرد')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='الرقم التسلسلي')),
                ('barcode', models.CharField(blank=True, max_length=100, verbose_name='الباركود')),
                ('status', models.CharField(choices=[('available', 'متوفر'), ('assigned', 'مخرج/مسلم'), ('maintenance', 'في الصيانة'), ('disposed', 'متلف/محذوف')], default='available', max_length=20, verbose_name='الحالة')),
                ('condition', models.CharField(choices=[('new', 'جديد'), ('good', 'جيد'), ('fair', 'مقبول'), ('poor', 'سيء'), ('damaged', 'تالف')], default='new', max_length=20, verbose_name='حالة المادة')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الشراء')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='سعر الشراء')),
                ('warranty_end', models.DateField(blank=True, null=True, verbose_name='نهاية الضمان')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_items', to='inventory.department', verbose_name='المصلحة المستفيدة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='core.tenant', verbose_name='الوحدة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'عنصر مخزون',
                'verbose_name_plural': 'عناصر المخزون',
                'ordering': ['-created_at'],
                'unique_together': {('inventory_number', 'tenant')},
            },
        ),
    ]
