# Generated by Django 6.0.2 on 2026-02-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='الكمية الأولية'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='الكمية المتوفرة'),
        ),
    ]
