# Generated by Django 6.0.2 on 2026-02-04 08:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposalVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50, verbose_name='رقم الوصل')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('disposal_reason', models.CharField(choices=[('damaged', 'تلف'), ('obsolete', 'تقادم'), ('lost', 'ضياع'), ('theft', 'سرقة'), ('other', 'أخرى')], max_length=20, verbose_name='سبب الإتلاف')),
                ('disposal_details', models.TextField(blank=True, verbose_name='تفاصيل الإتلاف')),
                ('committee_members', models.TextField(blank=True, help_text='أسماء أعضاء لجنة الإتلاف', verbose_name='أعضاء اللجنة')),
                ('disposal_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإتلاف الفعلي')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='أكد بواسطة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'وصل إتلاف',
                'verbose_name_plural': 'وصلات الإتلاف',
                'ordering': ['-date', '-created_at'],
                'abstract': False,
                'unique_together': {('voucher_number', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='DisposalVoucherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية')),
                ('damage_description', models.TextField(blank=True, verbose_name='وصف التلف')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='المنتج')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.disposalvoucher', verbose_name='الوصل')),
            ],
            options={
                'verbose_name': 'عنصر وصل إتلاف',
                'verbose_name_plural': 'عناصر وصل الإتلاف',
            },
        ),
        migrations.CreateModel(
            name='DisposalVoucherAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem', verbose_name='عنصر المخزون')),
                ('voucher_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='transactions.disposalvoucheritem', verbose_name='عنصر الوصل')),
            ],
            options={
                'verbose_name': 'أصل متلف',
                'verbose_name_plural': 'الأصول المتلفة',
            },
        ),
        migrations.CreateModel(
            name='EntryVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50, verbose_name='رقم الوصل')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='رقم الفاتورة')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الفاتورة')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='أكد بواسطة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_vouchers', to='inventory.supplier', verbose_name='المورد')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'وصل دخول',
                'verbose_name_plural': 'وصلات الدخول',
                'ordering': ['-date', '-created_at'],
                'abstract': False,
                'unique_together': {('voucher_number', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='EntryVoucherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='سعر الوحدة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='المنتج')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.entryvoucher', verbose_name='الوصل')),
            ],
            options={
                'verbose_name': 'عنصر وصل دخول',
                'verbose_name_plural': 'عناصر وصل الدخول',
            },
        ),
        migrations.CreateModel(
            name='EntryVoucherAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem', verbose_name='عنصر المخزون')),
                ('voucher_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='transactions.entryvoucheritem', verbose_name='عنصر الوصل')),
            ],
            options={
                'verbose_name': 'أصل مدخل',
                'verbose_name_plural': 'الأصول المدخلة',
            },
        ),
        migrations.CreateModel(
            name='ExitVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50, verbose_name='رقم الوصل')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('recipient_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المستلم')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='أكد بواسطة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_vouchers', to='inventory.department', verbose_name='المصلحة المستفيدة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'وصل إخراج',
                'verbose_name_plural': 'وصلات الإخراج',
                'ordering': ['-date', '-created_at'],
                'abstract': False,
                'unique_together': {('voucher_number', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='ExitVoucherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='المنتج')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.exitvoucher', verbose_name='الوصل')),
            ],
            options={
                'verbose_name': 'عنصر وصل إخراج',
                'verbose_name_plural': 'عناصر وصل الإخراج',
            },
        ),
        migrations.CreateModel(
            name='ExitVoucherAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem', verbose_name='عنصر المخزون')),
                ('voucher_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='transactions.exitvoucheritem', verbose_name='عنصر الوصل')),
            ],
            options={
                'verbose_name': 'أصل مخرج',
                'verbose_name_plural': 'الأصول المخرجة',
            },
        ),
        migrations.CreateModel(
            name='ReturnVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50, verbose_name='رقم الوصل')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('return_reason', models.TextField(blank=True, verbose_name='سبب الإرجاع')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='أكد بواسطة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_vouchers', to='inventory.department', verbose_name='المصلحة المرجعة')),
                ('original_exit_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_vouchers', to='transactions.exitvoucher', verbose_name='وصل الإخراج الأصلي')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'وصل إرجاع',
                'verbose_name_plural': 'وصلات الإرجاع',
                'ordering': ['-date', '-created_at'],
                'abstract': False,
                'unique_together': {('voucher_number', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='ReturnVoucherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية')),
                ('condition', models.CharField(choices=[('good', 'جيد'), ('fair', 'مقبول'), ('damaged', 'تالف')], default='good', max_length=20, verbose_name='حالة المادة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='المنتج')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.returnvoucher', verbose_name='الوصل')),
            ],
            options={
                'verbose_name': 'عنصر وصل إرجاع',
                'verbose_name_plural': 'عناصر وصل الإرجاع',
            },
        ),
        migrations.CreateModel(
            name='ReturnVoucherAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem', verbose_name='عنصر المخزون')),
                ('voucher_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='transactions.returnvoucheritem', verbose_name='عنصر الوصل')),
            ],
            options={
                'verbose_name': 'أصل مرجع',
                'verbose_name_plural': 'الأصول المرجعة',
            },
        ),
    ]
